### ISSUE TITLE
deleting structures multipllies coal-mine count

### ISSUE THREAD

**Issue by 8bitkerbal** [zakmasood/HexRedone#3] opened 2024-07-04 17:25 UTC
## Describe the bug
Each time you delete a structure, the amount of Coal-mines gets multiplied by an unspecified value

### Steps to reproduce
just place a bunch of coal mines, click them twice while they're producing coal, then delete other structures

### Expected behavior
coal-mine count to go down instead of multiply...
![Screenshot 2024-07-04 192207](https://github.com/zakmasood/HexRedone/assets/174737409/ab3341eb-5d2b-4cce-8375-b57f88f757fa)

### Environment
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

**Comment by zakmasood** [comment] 2024-07-04 17:27
Not sure of the cause, will look into it

**Comment by zakmasood** [comment] 2024-07-05 19:07
Resolved with #4

**Comment by zakmasood** [comment] 2024-07-05 19:07
Resolved with Issue #4, factory deletion function added.

**Closed as completed by zakmasood** 2024-07-05 19:07 UTC
Labels: bug
